-- AlterTable
ALTER TABLE "countdowntimers" ALTER COLUMN "text_promotion" SET DEFAULT 'VEJA A OFERTA POR TEMPO LIMITADO!!!',
ALTER COLUMN "text_button" SET DEFAULT 'OFERTA AQUI!!!',
ALTER COLUMN "day" SET DEFAULT '31',
ALTER COLUMN "month" SET DEFAULT '12',
ALTER COLUMN "year" SET DEFAULT '2024',
ALTER COLUMN "hour" SET DEFAULT '23',
ALTER COLUMN "minute" SET DEFAULT '55',
ALTER COLUMN "second" SET DEFAULT '20',
ALTER COLUMN "link_button" SET DEFAULT 'https://builderseunegocioonline.com.br';
